name: Installer

on: push
  #push:
  #  tags:
  #    - "v*.*.*"
      
permissions:
  contents: write

jobs:
  installer:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: ['3.2.1']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Ruby 3.2.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Create Core Lich-5 package
        id: install_core_scripts
        run: |
          ruby --version
          gem install ascii_charts ftools gtk3 json jwt mechanize net-https nokogiri redis rubygems sequel socket sqlite3 terminal-table tzinfo webrick xmpp4r
          gem list
